apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: s3-provider
  name: s3-provider
spec:
  selector:
    matchLabels:
      app: s3-provider
  template:
    metadata:
      labels:
        app: s3-provider
    spec:
      containers:
      - name: s3fuse
        image: absortian/s3-mounter:1.0.0
        securityContext:
          privileged: true
        envFrom:
        - secretRef:
            name: s3-config
        volumeMounts:
        # Fuse necessary for mounting
        - name: devfuse
          mountPath: /dev/fuse
        # Mounting points for buckets
        - name: bucket-one
          mountPath: /mnt/bucket-one
          mountPropagation: Bidirectional
      volumes:
      # Fuse necessary for mounting
      - name: devfuse
        hostPath:
          path: /dev/fuse
      # Mounting points for buckets
      - name: bucket-one
        hostPath:
          path: /mnt/bucket-one
