apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    app: s3-provider
  name: s3-provider
spec:
  template:
    metadata:
      labels:
        app: s3-provider
    spec:
      containers:
      - name: s3fuse
        image: dockerhub.io/meain/s3-mounter
        securityContext:
          privileged: true
        envFrom:
        - secretRef:
            name: s3-config
        volumeMounts:
        # Fuse necessary for mounting
        - name: devfuse
          mountPath: /dev/fuse
        # Mounting points for buckets
        - name: bucket-one
          mountPath: /mnt/bucket-one:shared
      volumes:
      # Fuse necessary for mounting
      - name: devfuse
        hostPath:
          path: /dev/fuse
      # Mounting points for buckets
      - name: bucket-one
        hostPath:
          path: /mnt/bucket-one
