apiVersion: v1
kind: Secret
metadata:
  name: s3-config
data:
  # Base64 encoded values
  MOUNT_JSON: '[{"bucket-one": "/mnt/bucket-one"}]'
  S3_KEY: 'exampleKey'
  S3_SECRET: 'exampleSecret'
  S3_URL: 'https://s3.test.example'
  S3_USE_PATH_REQUEST_STYLE: 'true'
